linters:
    eslint:
        config: './.eslintrc.json'

fixers:
    enable: true

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'
        - 'node_modules/*'
  csslint: {  }
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
